---
version: "2"

linters:
  default: all
  disable:
    - testpackage
    - forbidigo
    - godox
    - depguard
    - revive
    - noinlineerr
    - wsl
    - gomodguard
    - exhaustruct       # deprecated, replaced by exhaustruct_v5
