builds:
  - 
    gcflags:
      - all=-trimpath={{.Env.GOPATH}}
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.CommitDate}} -X main.builtBy=goreleaser
